default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("RECIPES_DATABASE_HOST") { "localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: recipes_development
  username: root
  password:
  socket: /tmp/mysql.sock
test:
  <<: *default
  database: recipes_test
  username: root
  password:
  socket: /tmp/mysql.sock
production:
  <<: *default
  database: recipes_production
  username: recipes_production
  password: <%= ENV["RECIPES_PASSWORD"] %>
staging:
  <<: *default
  database: recipes_staging
  username: recipes_staging
  password: <%= ENV["RECIPES_PASSWORD"] %>
